version: "3.8"

services:
  zoostoredb:
    container_name: zoostoredb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zoostoredb
    networks:
      springboot-mysql-net:
  zoostore:
    container_name: springboot-rest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      springboot-mysql-net:
    restart: on-failure
    depends_on:
      - zoostoredb

networks:
  springboot-mysql-net: